<?php
$socials = array (
  0 => 
  array (
    'id' => 1,
    'title' => 'Facebook',
    'slug' => 'facebook',
    'url' => 'https://facebook.com/#facebook',
    'icon' => 'fab fa-facebook-f',
    'og_title' => NULL,
    'og_image' => NULL,
    'og_description' => NULL,
    'status' => 'active',
    'created_by' => 1,
    'created_at' => '2022-10-19 07:08:28',
    'updated_at' => '2022-10-19 07:11:52',
    'deleted_at' => NULL,
  ),
  1 => 
  array (
    'id' => 2,
    'title' => 'LinkedIn',
    'slug' => 'linkedin',
    'url' => 'https://linkedin.com/#linkedin',
    'icon' => 'fab fa-linkedin-in',
    'og_title' => NULL,
    'og_image' => NULL,
    'og_description' => NULL,
    'status' => 'active',
    'created_by' => 1,
    'created_at' => '2022-10-19 07:10:00',
    'updated_at' => '2022-10-19 07:11:47',
    'deleted_at' => NULL,
  ),
  2 => 
  array (
    'id' => 3,
    'title' => 'Youtube',
    'slug' => 'youtube',
    'url' => 'https://youtube.com/#youtube',
    'icon' => 'fab fa-youtube',
    'og_title' => NULL,
    'og_image' => NULL,
    'og_description' => NULL,
    'status' => 'active',
    'created_by' => 1,
    'created_at' => '2022-10-19 07:10:47',
    'updated_at' => '2022-10-19 07:10:47',
    'deleted_at' => NULL,
  ),
  3 => 
  array (
    'id' => 4,
    'title' => 'Instagram',
    'slug' => 'instagram',
    'url' => 'https://instagram.com/#instagram',
    'icon' => 'fab fa-instagram',
    'og_title' => NULL,
    'og_image' => NULL,
    'og_description' => NULL,
    'status' => 'active',
    'created_by' => 1,
    'created_at' => '2022-10-19 07:11:26',
    'updated_at' => '2022-10-19 07:11:26',
    'deleted_at' => NULL,
  ),
);
return $socials;
