<?php
$switch_units = array (
  0 =>
  array (
    'id' => 1,
    'name' => 'Switch Unit 1',
    'serial_number' => 'switch-unit-1',
    'slug' => 'switch-unit-1',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:12:57',
    'updated_at' => '2024-03-24 01:01:35',
    'deleted_at' => NULL,
  ),
  1 =>
  array (
    'id' => 2,
    'name' => 'Switch Unit 2',
    'serial_number' => 'switch-unit-2',
    'slug' => 'switch-unit-2',
    'switches' => '[{"number":"1","switchType":"2","status":"on","comment":"C1"},{"number":"2","switchType":"1","status":"on","comment":null},{"number":"3","switchType":"2","status":"on","comment":null},{"number":"4","switchType":"1","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"2","status":"on","comment":"C8"},{"number":"9","switchType":"2","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"2","status":"on","comment":null},{"number":"12","switchType":"1","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  2 =>
  array (
    'id' => 3,
    'name' => 'Switch Unit 3',
    'serial_number' => 'switch-unit-3',
    'slug' => 'switch-unit-3',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  3 =>
  array (
    'id' => 4,
    'name' => 'Switch Unit 4',
    'serial_number' => 'switch-unit-4',
    'slug' => 'switch-unit-4',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  4 =>
  array (
    'id' => 5,
    'name' => 'Switch Unit 5',
    'serial_number' => '27',
    'slug' => 'switch-unit-5',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  5 =>
  array (
    'id' => 6,
    'name' => 'Switch Unit 6',
    'serial_number' => '26',
    'slug' => 'switch-unit-6',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  6 =>
  array (
    'id' => 7,
    'name' => 'Switch Unit 7',
    'serial_number' => 'switch-unit-7',
    'slug' => 'switch-unit-7',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  7 =>
  array (
    'id' => 8,
    'name' => 'Switch Unit 8',
    'serial_number' => 'switch-unit-8',
    'slug' => 'switch-unit-8',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  8 =>
  array (
    'id' => 9,
    'name' => 'Switch Unit 9',
    'serial_number' => 'switch-unit-9',
    'slug' => 'switch-unit-9',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  9 =>
  array (
    'id' => 10,
    'name' => 'Switch Unit 10',
    'serial_number' => 'switch-unit-10',
    'slug' => 'switch-unit-10',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  10 =>
  array (
    'id' => 11,
    'name' => 'Switch Unit 11',
    'serial_number' => 'switch-unit-11',
    'slug' => 'switch-unit-11',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"on","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-03-24 01:03:35',
    'deleted_at' => NULL,
  ),
  11 =>
  array (
    'id' => 12,
    'name' => 'Switch Unit 12',
    'serial_number' => 'switch-unit-12',
    'slug' => 'switch-unit-12',
    'switches' => '[{"number":"1","switchType":"1","status":"on","comment":"C1"},{"number":"2","switchType":"2","status":"off","comment":null},{"number":"3","switchType":"1","status":"on","comment":null},{"number":"4","switchType":"2","status":"on","comment":null},{"number":"5","switchType":"1","status":"on","comment":null},{"number":"6","switchType":"1","status":"on","comment":null},{"number":"7","switchType":"2","status":"on","comment":null},{"number":"8","switchType":"1","status":"on","comment":"C8"},{"number":"9","switchType":"1","status":"on","comment":null},{"number":"10","switchType":"1","status":"on","comment":"C10"},{"number":"11","switchType":"1","status":"on","comment":null},{"number":"12","switchType":"2","status":"on","comment":"C12"}]',
    'description' => NULL,
    'status' => 'active',
    'created_by' => 4,
    'created_at' => '2024-03-24 00:13:19',
    'updated_at' => '2024-04-02 02:54:22',
    'deleted_at' => NULL,
  ),
);
return $switch_units;
