<?php
$users = array (
  0 =>
  array (
    'id' => 1,
    'name' => 'Afzalur Rahman Sabbir',
    'email' => 'afzalbd1@gmail.com',
    'username' => 'afzalbd1',
    'email_verified_at' => '2023-01-18 21:05:15',
    'password' => '$2y$10$G0obDvT5v6fRNM.JUNYTLOZbHvBtB2eIuTAQra5GZ3PzBmQLg.lWW',
    'is_admin' => 1,
    'remember_token' => 'Cx7loqLMDsHwXeh9izEE7WcAGPjL2HvUNKkAXymMMgd4pHKWLW92AlXar40M',
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  1 =>
  array (
    'id' => 2,
    'name' => 'Admin',
    'email' => 'admin@yopmail.com',
    'username' => 'admin',
    'email_verified_at' => NULL,
    'password' => '$2y$10$qXLHzXgR2MwIsxeyyDgFEOonsN0m1ET29JRht6NBVQ8Rim21jhF.u',
    'is_admin' => 1,
    'remember_token' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  2 =>
  array (
    'id' => 3,
    'name' => 'User',
    'email' => 'user@yopmail.com',
    'username' => 'user',
    'email_verified_at' => NULL,
    'password' => '$2y$10$jxfSScf5ClZRPSy76ZNedudsd7pUBYeUnVUMzPxHBJEPsYS/RuIlq',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  3 =>
  array (
    'id' => 4,
    'name' => 'Super Admin',
    'email' => 'superadmin@yopmail.com',
    'username' => 'superadmin',
    'email_verified_at' => NULL,
    'password' => '$2a$12$NMYqJXW3s8.LSURNY9lhfuXwDccCLPrZxQ.G81KL3M45J93KBrzXy',
    'is_admin' => 1,
    'remember_token' => 'NUkcqw6GdE7qyf8T6Gqkaafg60Pl8hJuJh0kqEn3m5I2hf7P8DI94pv9Rcw8',
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  4 =>
  array (
    'id' => 5,
    'name' => 'Customer 1',
    'email' => 'customer-1@yopmail.com',
    'username' => 'customer-1',
    'email_verified_at' => NULL,
    'password' => '$2y$10$t.2zItf1QrcH0hMzM70GOeTfc/oMRD1/6PVnGqJNm8SRKuf47BCVK',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-03-06 02:12:38',
    'updated_at' => '2024-03-06 02:12:38',
    'deleted_at' => NULL,
  ),
  5 =>
  array (
    'id' => 6,
    'name' => 'Customer 2',
    'email' => 'customer-2@yopmail.com',
    'username' => 'customer-2',
    'email_verified_at' => NULL,
    'password' => '$2y$10$NU9MdxQrPHKp8RgEkH3fzOpeq.p.QT09ds.P.sw33tpEw0hlGgw5e',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-03-06 02:13:02',
    'updated_at' => '2024-03-06 02:13:02',
    'deleted_at' => NULL,
  ),
  6 =>
  array (
    'id' => 7,
    'name' => 'Customer 3',
    'email' => 'customer-3@yopmail.com',
    'username' => 'customer-3',
    'email_verified_at' => NULL,
    'password' => '$2y$10$.p8iJocWTeH8kMm94Z5Tr.xCD5lO/LNUMJ6R1YLaJ/FXPqJJ7ZXZC',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-03-06 02:13:20',
    'updated_at' => '2024-03-06 02:13:20',
    'deleted_at' => NULL,
  ),
);
return $users;
