<?php
$users = array (
  0 =>
  array (
    'id' => 1,
    'name' => 'Nexus Fish Network',
    'email' => 'afzalbd1@gmail.com',
    'username' => 'afzalbd1',
    'email_verified_at' => '2023-01-19 03:05:15',
    'password' => '$2y$10$G0obDvT5v6fRNM.JUNYTLOZbHvBtB2eIuTAQra5GZ3PzBmQLg.lWW',
    'is_admin' => 1,
    'remember_token' => 'NQbleYrG95e7ErYCxieNfeTj6PYuxcaPttdoK6zhiUk2pEC36Jimh5V7bD8d',
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  1 =>
  array (
    'id' => 2,
    'name' => 'Admin',
    'email' => 'admin@gmail.com',
    'username' => 'admin@gmail.com',
    'email_verified_at' => NULL,
    'password' => '$2y$10$5XPBl1lMO1rSQIGPPcx.Ku27E4BaRCZ658OmE02w8DNLV801w10HC',
    'is_admin' => 1,
    'remember_token' => 'Xmi65b36udsaJS8UXQ8PnaW2SCC3LYcRLW5raNVbVE86LsxidZGdSPsLyfTv',
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  2 =>
  array (
    'id' => 3,
    'name' => 'User',
    'email' => 'user@yopmail.com',
    'username' => 'user',
    'email_verified_at' => NULL,
    'password' => '$2y$10$jxfSScf5ClZRPSy76ZNedudsd7pUBYeUnVUMzPxHBJEPsYS/RuIlq',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  3 =>
  array (
    'id' => 4,
    'name' => 'Super Admin',
    'email' => 'superadmin@yopmail.com',
    'username' => 'superadmin',
    'email_verified_at' => NULL,
    'password' => '$2a$12$NMYqJXW3s8.LSURNY9lhfuXwDccCLPrZxQ.G81KL3M45J93KBrzXy',
    'is_admin' => 1,
    'remember_token' => 'qh0I7pcSMCQVXvDczMALStOUPW8pPZsrOtwDanvPhMddDY59TDoNeCS6nBJn',
    'created_at' => NULL,
    'updated_at' => NULL,
    'deleted_at' => NULL,
  ),
  4 =>
  array (
    'id' => 5,
    'name' => 'Customer-1 Yopmail',
    'email' => 'customer-1@yopmail.com',
    'username' => 'customer-1',
    'email_verified_at' => NULL,
    'password' => '$2y$10$t.2zItf1QrcH0hMzM70GOeTfc/oMRD1/6PVnGqJNm8SRKuf47BCVK',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-03-06 08:12:38',
    'updated_at' => '2024-03-25 20:29:22',
    'deleted_at' => NULL,
  ),
  5 =>
  array (
    'id' => 6,
    'name' => 'Customer-2 Yopmail',
    'email' => 'customer-2@yopmail.com',
    'username' => 'customer-2',
    'email_verified_at' => NULL,
    'password' => '$2y$10$NU9MdxQrPHKp8RgEkH3fzOpeq.p.QT09ds.P.sw33tpEw0hlGgw5e',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-03-06 08:13:02',
    'updated_at' => '2024-03-25 20:29:36',
    'deleted_at' => NULL,
  ),
  6 =>
  array (
    'id' => 7,
    'name' => 'Customer-3 Yopmail',
    'email' => 'customer-3@yopmail.com',
    'username' => 'customer-3',
    'email_verified_at' => NULL,
    'password' => '$2y$10$.p8iJocWTeH8kMm94Z5Tr.xCD5lO/LNUMJ6R1YLaJ/FXPqJJ7ZXZC',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-03-06 08:13:20',
    'updated_at' => '2024-03-25 20:28:26',
    'deleted_at' => NULL,
  ),
  7 =>
  array (
    'id' => 8,
    'name' => 'Sumon dev',
    'email' => 'sumondev799@gmail.com',
    'username' => 'sumondev799',
    'email_verified_at' => NULL,
    'password' => '$2y$10$qc7/BOIYWN4hdPtKl7b3veQ1TJt1LkPLg79z1kSXXkKu4Rl1x9DVm',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-04-22 20:42:37',
    'updated_at' => '2024-04-22 20:42:37',
    'deleted_at' => NULL,
  ),
  8 =>
  array (
    'id' => 9,
    'name' => 'Test Customer',
    'email' => 'test@email.com',
    'username' => 'tester',
    'email_verified_at' => NULL,
    'password' => '$2y$10$kqPIQOuM.CCYIBGojlSiFeenHpRJ0l5jm.uw5rq52BqXDzmTIlNdu',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-04-23 02:48:34',
    'updated_at' => '2024-04-23 02:57:35',
    'deleted_at' => NULL,
  ),
  9 =>
  array (
    'id' => 10,
    'name' => 'Erfan Tushar',
    'email' => 'erfanmahmud642@gmail.com',
    'username' => 'we_test',
    'email_verified_at' => NULL,
    'password' => '$2y$10$Q7GW.O7FXx4ATIaQNeFYEOokFqrTTpEp8rw959jAKvXHHS4i/8CUy',
    'is_admin' => 0,
    'remember_token' => NULL,
    'created_at' => '2024-04-23 04:17:46',
    'updated_at' => '2024-04-30 14:22:29',
    'deleted_at' => NULL,
  ),
);
return $users;
